// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LaunchHyprland(arg1:string):Promise<string>;

export function OpenTTY():Promise<void>;

export function PowerOff():Promise<void>;

export function Reboot():Promise<void>;
