// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LaunchHyprland(arg1) {
  return window['go']['main']['App']['LaunchHyprland'](arg1);
}

export function OpenTTY() {
  return window['go']['main']['App']['OpenTTY']();
}

export function PowerOff() {
  return window['go']['main']['App']['PowerOff']();
}

export function Reboot() {
  return window['go']['main']['App']['Reboot']();
}
