:Loonix OS
    protocol: linux
    path: boot():/vmlinuz-linux-lts
    cmdline: root=UUID=55e61586-f684-4850-8079-37cff9d73f6d rw i915.modeset=1 nvidia-drm.modeset=1 quiet
    module_path: boot():/intel-ucode.img
    module_path: boot():/initramfs-linux-lts.img