general {
    lock_cmd = pidof hyprlock || hyprlock
    ignore_dbus_inhibit = false
}

listener {
    timeout = 480                                # 8min.
    on-timeout = brightnessctl -s set 10         # set monitor backlight to minimum, avoid 0 on OLED monitor.
    on-resume = brightnessctl -r                 # monitor backlight restore.
}

# turn off keyboard backlight, comment out this section if you dont have a keyboard backlight.
# listener { 
#     timeout = 480                                          # 8min.
#     on-timeout = brightnessctl -sd rgb:kbd_backlight set 0 # turn off keyboard backlight.
#     on-resume = brightnessctl -rd rgb:kbd_backlight        # turn on keyboard backlight.
# }

# 2. Lock Screen (COMMENT INI BIAR GAK MINTA PASSWORD TERUS)
listener {
timeout = 900                               # 15 menit
on-timeout = loginctl lock-session            
}

# 3. Matikan Layar (DPMS)
listener {
    timeout = 1800                                # 30 menit
    on-timeout = hyprctl dispatch dpms off        
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}

listener {
    timeout = 3600                                # 30min
    on-timeout = systemctl suspend                # suspend pc
}