# --- 🖥️ MONITOR SETTINGS ---------------------------------------------------
# Apply monitor presets via ddcutil (dibungkus uwsm)
exec-once = sleep 1 && uwsm app -- ddcutil setvcp 10 100 12 100 14 07 6C 40 6E 40 70 40 16 45 18 45 1a 45

# Set Cursor (Ini internal hyprctl, gak butuh uwsm app)
exec-once = hyprctl setcursor Volantes-Light 24

# --- 🛡️ SECURITY & CORE SERVICES -------------------------------------------
# Authentication Agent (Polkit) - Wajib pakai uwsm app
exec-once = uwsm app -- /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# GNOME Keyring
exec-once = uwsm app -- gnome-keyring-daemon --start --components=secrets

# Network Manager Applet
exec-once = uwsm app -- nm-applet --indicator

# --- 📋 CLIPBOARD MANAGER -------------------------------------------------
# Clipboard history
exec-once = uwsm app -- wl-paste --type text --watch cliphist store
exec-once = uwsm app -- wl-paste --type image --watch cliphist store

# --- 🔋 POWER & HARDWARE --------------------------------------------------
# Idle Management
exec-once = uwsm app -- hypridle

# --- TASKBAR ---------------------------------------------------
# Waybar dengan delay 2s
exec-once = sleep 2 && uwsm app -- waybar

# --- WP (WALLPAPER) ---------------------------------------------------
# Ini alasan layar lo item tadi. Sekarang harusnya nyala.
exec-once = uwsm app -- hyprpaper
