# 1. Paksa SEMUA jendela modal (pop-up konfirmasi/alert) buat melayang
windowrule = match:modal true, float on, center on

# 2. Paksa SEMUA jendela yang judulnya mengandung kata kunci dialog/pilih file
windowrule = match:title (.*)(Open|Select|Save|Choose|File|Folder)(.*), float on, center on, size 950 650

windowrule = match:float true, no_max_size on
# =========================================================
# LOONIX TUNES (Tiling Mode)
# =========================================================
windowrule {
  name = loonix-tunes-main
  match:class = loonix-tunes
  
  # MATIIN FLOAT biar dia mau Tiling
  float = off 
  
  # Override opacity biar tetep dapet glassmorphism Tokyo Night
  opacity = 0.85 override 0.85 override 
  
  # Pastiin blur aktif buat efek transparan di QML
  no_blur = off 
}


# =========================================================
# WOFI (Aura Theme Style)
# =========================================================
layerrule {
  name = wofi
  
  # Aktifin blur (pake on/off atau 1/0)
  blur = on
  
  # Set animasi ke popin
  animation = popin
}


