# 1. Paksa SEMUA jendela modal (pop-up konfirmasi/alert) buat melayang
windowrule = match:modal true, float on, center on

# 2. Paksa SEMUA jendela yang judulnya mengandung kata kunci dialog/pilih file
windowrule = match:title (.*)(Open|Select|Save|Choose|File|Folder)(.*), float on, center on, size 950 650

windowrule = match:float true, no_max_size on

# =========================================================
# LOONIX TUNES (lt) RULES
# =========================================================
windowrule {
  name = loonix-tunes-main
  match:class = loonix-tunes
  float = on
  center = on
  size = 900 600
  # Gunakan override biar gak nabrak setting global opacity lu
  opacity = 0.85 override 0.85 override 
  
  # Kalau mau mastiin blur aktif, jangan di-disable
  no_blur = off 
}


