# 1. Paksa SEMUA jendela modal (pop-up konfirmasi/alert) buat melayang
windowrule = match:modal true, float on, center on

# 2. Paksa SEMUA jendela yang judulnya mengandung kata kunci dialog/pilih file
windowrule = match:title (.*)(Open|Select|Save|Choose|File|Folder)(.*), float on, center on, size 950 650

windowrule = match:float true, no_max_size on